package hanoi.towers.module.db.migrations

import hanoi.towers.module.db.schema.User
import hanoi.towers.module.db.schema.Users
import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Mon Apr 01 22:02:29 CEST 2024
 *
 * Description: ...
 */
class Migration1712001749830(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1712001749830

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {

        SchemaUtils.create(Users)

        val smith = User.new {
            username = "schmidt@alpha-structure.com"
            password = "pass1234"
        }
        val sulz = User.new {
            username = "florian.schmidt@sulzer.de"
            password = "pass1234"
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     * These migrations are not taken into account by now!
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}