package hanoi.towers.data.pages.cheat.component

import hanoi.towers.data.hanoi.Hanoi
import lib.language.Lang
import lib.optics.Lensify
import lib.optics.ReadOnly
import lib.optics.ReadWrite
import lib.optics.lens.Lens

@Lensify data class HanoiCheat(
    @ReadWrite val hanoi: Hanoi,
    @ReadOnly val texts: Lang,
    @ReadOnly val maxNumberOfSlices: Int = 10
)

/**
 * Autogenerated Lens.
 * Read and manipulate [HanoiCheat.hanoi]
 */
@ReadWrite val hanoi: Lens<HanoiCheat, Hanoi> by lazy{ Lens(
    get = {whole -> whole.hanoi},
    set = {part -> {whole -> whole.copy(hanoi = part)}}
) }

/**
 * Autogenerated ReadOnly Lens.
 * Read [HanoiCheat.texts]
 */
@ReadOnly val texts: Lens<HanoiCheat, Lang> by lazy{ Lens(
    get = {whole -> whole.texts},
    set = {{it}}
) }

/**
 * Autogenerated ReadOnly Lens.
 * Read [HanoiCheat.maxNumberOfSlices]
 */
@ReadOnly val maxNumberOfSlices: Lens<HanoiCheat, Int> by lazy{ Lens(
    get = {whole -> whole.maxNumberOfSlices},
    set = {{it}}
) }
