package hanoi.towers.data.navigation

import hanoi.towers.data.i18n.I18N
import lib.optics.Lensify
import lib.optics.ReadWrite
import lib.optics.lens.Lens

@Lensify data class NavBar(
    @ReadWrite val i18n: I18N,
)


/**
 * Autogenerated Lens.
 * Read and manipulate [NavBar.i18n]
 */
@ReadWrite val i18n: Lens<NavBar, I18N> by lazy{ Lens(
    get = {whole -> whole.i18n},
    set = {part -> {whole -> whole.copy(i18n = part)}}
) }