package hanoi.towers.data.navigation

import hanoi.towers.data.environment.Environment
import hanoi.towers.data.i18n.I18N
import lib.optics.Lensify
import lib.optics.ReadOnly
import lib.optics.ReadWrite
import lib.optics.lens.Lens

@Lensify data class NavBar(
    @ReadWrite val i18n: I18N,
    @ReadOnly val environment: Environment
)


/**
 * Autogenerated Lens.
 * Read and manipulate [NavBar.i18n]
 */
@ReadWrite val i18n: Lens<NavBar, I18N> by lazy{ Lens(
    get = {whole -> whole.i18n},
    set = {part -> {whole -> whole.copy(i18n = part)}}
) }

/**
 * Autogenerated Lens.
 * Read and manipulate [NavBar.i18n]
 */
@ReadWrite val environment: Lens<NavBar, Environment> by lazy{ Lens(
    get = {whole -> whole.environment},
    set = {_->{whole -> whole}}
) }
