package hanoi.towers.data.cookies

import lib.optics.Lensify
import lib.optics.ReadWrite
import lib.optics.lens.Lens

@Lensify data class Cookies(
    @ReadWrite val isCookieDisclaimerConfirmed: Boolean,
)

/**
 * Autogenerated Lens.
 * Read and manipulate [Cookies.isCookieDisclaimerConfirmed]
 */
@ReadWrite val isCookieDisclaimerConfirmed: Lens<Cookies, Boolean> by lazy {
    Lens(
        get = { whole -> whole.isCookieDisclaimerConfirmed },
        set = { part -> { whole -> whole.copy(isCookieDisclaimerConfirmed = part) } }
    )
}
