package org.evoleq.exposedx.migration

import org.gradle.api.Project
import org.gradle.kotlin.dsl.invoke
import java.io.File
import java.util.*

fun generateMigration(id: Long, packageName: String): String =
    """
        |package $packageName
        |
        |import org.evoleq.exposedx.migrations.Migration
        |import org.jetbrains.exposed.sql.Database
        |import org.jetbrains.exposed.sql.Transaction
        |
        |/**
        | * Autogenerated [Migration],
        | * generated by the evoleq/exposedx migration gradle-plugin.
        | * Alter with care!
        | *
        | * Generated at ${Date(id)}
        | *
        | * Description: ...
        | */
        |class Migration$id(
        |    override val database: Database
        |) : Migration {
        |
        |    /**
        |     * Id of the migration, do not change!
        |     */
        |    override val id: Long
        |        get() = $id
        |
        |    /**
        |     * Upwards migration
        |     */
        |    override suspend fun Transaction.up() {
        |        TODO("Not yet implemented")
        |    }
        |
        |    /**
        |     * Downwards migration (inverse to the upward migration).
        |     * These migrations are not taken into account by now!
        |     */
        |    override suspend fun Database.down() {
        |        TODO("Not yet implemented")
        |    }
        |}
        """.trimMargin()

fun File.buildMigrationList(packageName: String, module: String = ""): String {
    val migrations = listFiles {
            file -> with(file.name) {
                startsWith("migration-") &&
                endsWith(".kt")
        }
    }?.map{
        it.name.substring(10).dropLast(3)
    }?.map{
        it.toLong()
    }?.sortedBy{
        it
    }?.map{
        "        { Migration${it}(this) }"
    }?: listOf()
    
    val migrationListName = when(module) {
        "" -> "migrations"
        else -> module + "Migrations"
    }
    
    return """
    |package $packageName
    |
    |import org.evoleq.exposedx.migrations.Migration
    |import org.jetbrains.exposed.sql.Database
    |
    |/**
    | * Autogenerated [List] of [Migration]s. Alter with care!
    | */
    |val ${migrationListName}: ArrayList<Database.()-> Migration> by lazy{
    |    arrayListOf<Database.()-> Migration>(
    |${migrations.joinToString(",\n") { it }}
    |    )
    |}
    """.trimMargin()
}


fun Project.migrations(packageName: String) {
    tasks{
        
        val generateMigrationTask = register("generate-migration") {
            group = "migration"
            doLast {
                val id = System.currentTimeMillis()
                val migrationText = generateMigration(
                    id,
                    packageName
                )
        
                val file = File(
                    "${project.rootDir.absolutePath}/${project.name}/src/main/kotlin/${
                        packageName.replace(
                            ".",
                            "/"
                        )
                    }/migration-$id.kt"
                )
                println(file.absolutePath)
        
                file.writeText(migrationText)
                println(migrationText)
                val migrationsFolder = file.parentFile
                with(migrationsFolder) {
                    File(this, "migrations.kt").writeText(
                        buildMigrationList(
                            packageName
                        )
                    )
                }
            }.finalizedBy(
                //"licenseFormat"
            )
            
        }
        /*
        generateMigrationTask {
            onlyIf { project.hasProperty("generate-migration") }
        }
        
        
         */
    }
}

fun Project.migrations(domain: String, module: String, migrations: String) {
    tasks{
        
        val generateMigrationTask = register("$module-generate-migration") {
            group = "migration"
            doLast {
                val id = System.currentTimeMillis()
                val packageName = if(module != "application"){
                    "$domain.module.$module.$migrations"
                }else{
                    "$domain.$module.$migrations"
                }
                
                val migrationText = generateMigration(
                    id,
                    packageName
                )
    
                val file = File(
                    "${project.rootDir.absolutePath}/${project.name}/src/main/kotlin/${
                        domain.replace(
                            ".",
                            "/"
                        )
                    }${if(module != "application"){"/module"}else {""}}/$module/$migrations/migration-$id.kt"
                )
                println(file.absolutePath)
    
                file.writeText(migrationText)
                println(migrationText)
                
                val migrationsFolder = file.parentFile
                with(migrationsFolder) {
                    File(this, "migrations.kt").writeText(
                        buildMigrationList(
                            packageName,
                            module
                        )
                    )
                }
                //println(file.parentFile.buildMigrationList())
            }.finalizedBy(
                //"licenseFormat"
            )
        }
    /*
        generateMigrationTask {
            onlyIf { project.hasProperty("$module-generate-migration") }
        }
      */
    }
}