@file:Suppress("MatchingDeclarationName")
package hanoi.towers.data.pages.main

import lib.language.Lang
import lib.optics.Lensify
import lib.optics.ReadOnly
import lib.optics.lens.Lens


@Lensify data class Main(
    @ReadOnly val texts: Lang,
)


/**
 * Autogenerated ReadOnly Lens.
 * Read [Main.texts]
 */
@ReadOnly val texts: Lens<Main, Lang> by lazy{ Lens(
    get = {whole -> whole.texts},
    set = {{it}}
) }
