package hanoi.towers.data.pages.cheat

import hanoi.towers.data.hanoi.Moves
import hanoi.towers.data.pages.cheat.component.HanoiCheat
import lib.language.Lang
import lib.optics.Lensify
import lib.optics.ReadOnly
import lib.optics.ReadWrite
import lib.optics.lens.Lens

@Lensify data class HanoiCheatPage(
    @ReadOnly val texts: Lang.Block,
    @ReadWrite val cheat: HanoiCheat,
    @ReadWrite val numberOfSlices: Int,
    @ReadWrite val numberOfMoves: Int,
    @ReadWrite val moves: Moves,
    @ReadWrite val isComputingMoves: Boolean,
    @ReadWrite val indexOfCurrentMove: Int,
    @ReadWrite val error: String?
)

/**
 * Autogenerated ReadOnly Lens.
 * Read [HanoiCheatPage.texts]
 */
@ReadOnly val texts: Lens<HanoiCheatPage, Lang.Block> by lazy {
    Lens(
        get = { whole -> whole.texts },
        set = { { it } }
    )
}

/**
 * Autogenerated Lens.
 * Read and manipulate [HanoiCheatPage.cheat]
 */
@ReadWrite val cheat: Lens<HanoiCheatPage, HanoiCheat> by lazy {
    Lens(
        get = { whole -> whole.cheat },
        set = { part -> { whole -> whole.copy(cheat = part) } }
    )
}

/**
 * Autogenerated Lens.
 * Read and manipulate [HanoiCheatPage.numberOfSlices]
 */
@ReadWrite val numberOfSlices: Lens<HanoiCheatPage, Int> by lazy {
    Lens(
        get = { whole -> whole.numberOfSlices },
        set = { part -> { whole -> whole.copy(numberOfSlices = part) } }
    )
}

/**
 * Autogenerated Lens.
 * Read and manipulate [HanoiCheatPage.numberOfMoves]
 */
@ReadWrite val numberOfMoves: Lens<HanoiCheatPage, Int> by lazy {
    Lens(
        get = { whole -> whole.numberOfMoves },
        set = { part -> { whole -> whole.copy(numberOfMoves = part) } }
    )
}

/**
 * Autogenerated Lens.
 * Read and manipulate [HanoiCheatPage.moves]
 */
@ReadWrite val moves: Lens<HanoiCheatPage, Moves> by lazy {
    Lens(
        get = { whole -> whole.moves },
        set = { part -> { whole -> whole.copy(moves = part) } }
    )
}

/**
 * Autogenerated Lens.
 * Read and manipulate [HanoiCheatPage.isComputingMoves]
 */
@ReadWrite val isComputingMoves: Lens<HanoiCheatPage, Boolean> by lazy {
    Lens(
        get = { whole -> whole.isComputingMoves },
        set = { part -> { whole -> whole.copy(isComputingMoves = part) } }
    )
}

/**
 * Autogenerated Lens.
 * Read and manipulate [HanoiCheatPage.indexOfCurrentMove]
 */
@ReadWrite val indexOfCurrentMove: Lens<HanoiCheatPage, Int> by lazy {
    Lens(
        get = { whole -> whole.indexOfCurrentMove },
        set = { part -> { whole -> whole.copy(indexOfCurrentMove = part) } }
    )
}

/**
 * Autogenerated Lens.
 * Read and manipulate [HanoiCheatPage.error]
 */
@ReadWrite val error: Lens<HanoiCheatPage, String?> by lazy {
    Lens(
        get = { whole -> whole.error },
        set = { part -> { whole -> whole.copy(error = part) } }
    )
}
