name: CD Pipeline Hanoi Towers
on:
  pull_request_target:
    branches:
      - master
      - develop
      - workflow-test # todo remove
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Prod Packages (FE, BE)
        run: echo "build"
      - name: Upload Artifacts
        run: echo "Uploading artifacts"
  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get artifacts
        run: "get artifacts"
      - name: setup/deploy to Test Env
        run: "Deploy to test env"
      - name: Run Tests
        run: echo "Run Tests"
  e2e-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: get artifacts
        run: "get artifacts"
      - name: setup/deploy to Test Env
        run: "Deploy to test env"
      - name: Run Tests
        run: echo "Run Tests"
  deploy:
    needs: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy"
  report:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Report
        run: echo "Report"