name: CI Pipeline Hanoi Towers
on:
  pull_request:
    branches:
      - master
      - develop
      - workflow-test # todo remove
    types:
      - opened # whenever a pr is created
      - synchronize # whenever something is pushed to an open pr
      #- closed # whenever a pr is closed

jobs:
  build-and-test-backend:
    outputs:
      lint: ${{ steps.lint.outputs.result }}
      build: ${{ steps.build.outputs.result }}
      test: ${{ steps.test.outputs.result }}
    runs-on: ubuntu-latest # there might be a better option
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Rest shall only run if there are changes in the backend-module
      - name: Setup JDK
        run: echo "Setting up JDK..."
      - name: Setup Gradle Project
        run: echo "Setting up Gradle Project..."
      - name: Lint
        id: lint
        run: |
          echo "Linting kotlin modules"
          echo "result=success" >> "$GITHUB_OUTPUT"
      - name: Build Project
        id: build
        run: |
          echo "Linting kotlin modules"
          echo "result=success" >> "$GITHUB_OUTPUT"
      - name: Run Tests
        id: test
        run: |
          echo "Running Tests"
          echo "result=success" >> "$GITHUB_OUTPUT"
  build-and-test-frontend:
    runs-on: ubuntu-latest # there might be a better option
    outputs:
      lint: ${{ steps.lint.outputs.result }}
      build: ${{ steps.build.outputs.result }}
      test: ${{ steps.test.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Rest shall only run if there are changes in the frontend-module
      - name: Setup JDK
        run: echo "Setting up JDK..."
      - name: Setup Gradle Project
        run: echo "Setting up Gradle Project..."
      - name: Lint
        id: lint
        run: |
          echo "Linting kotlin modules"
          echo "result=success" >> "$GITHUB_OUTPUT"
      - name: Build Project
        id: build
        run: |
          echo "Linting kotlin modules"
          echo "result=success" >> "$GITHUB_OUTPUT"
      - name: Run Tests
        id: test
        run: |
          echo "Running Tests"
          echo "result=success" >> "$GITHUB_OUTPUT"
  report:
    needs:
      - build-and-test-frontend
      - build-and-test-backend
    runs-on: ubuntu-latest # there might be a better option
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/studi-action

      - env:
          FE_LINT: ${{ needs.build-and-test-frontend.outputs.lint }}
          FE_BUILD: ${{ needs.build-and-test-frontend.outputs.build }}
          FE_TEST: ${{ needs.build-and-test-frontend.outputs.test }}
          BE_LINT: ${{ needs.build-and-test-backend.outputs.lint }}
          BE_BUILD: ${{ needs.build-and-test-backend.outputs.build }}
          BE_TEST: ${{ needs.build-and-test-backend.outputs.test }}
        run: |
          # Only for testing purpose
          echo "fe.lint.result = $FE_LINT"
          echo "fe.build.result = $FE_BUILD"
          echo "fe.test.result = $FE_TEST"
          
          echo "be.lint.result = $BE_LINT"
          echo "be.build.result = $BE_BUILD"
          echo "be.test.result = $BE_TEST"
            
          # Compute the overall result     
          results=("$FE_LINT" "$FE_BUILD" "$FE_TEST" "$BE_LINT" "$BE_BUILD" "$BE_TEST")     
          result=true
          for item in "${results[@]}"; do
            if [ $item != "success" ]
            then
              result=false
            fi
          done

          # TODO send report to developer when something has failed and complete job
          if $result; then
            exit 0
          else
            exit 1
          fi