uses: a11ywatch/github-action@v2.1.10
  with:
    WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
    SITE_WIDE: true
    SUBDOMAINS: true
    TLD: false
    SITEMAP: true
    FAIL_ERRORS_COUNT: 15
    LIST: true
    FIX: false
    UPGRADE: false
    UPLOAD: true
    COMPUTER_VISION_SUBSCRIPTION_KEY: ${{ secrets.COMPUTER_VISION_SUBSCRIPTION_KEY }}
    COMPUTER_VISION_ENDPOINT: ${{ secrets.COMPUTER_VISION_ENDPOINT }}
  env:
    DEFAULT_RUNNERS: htmlcs,axe
    PAGEMIND_IGNORE_WARNINGS: true
    AI_DISABLED: false
