name: CI Pipeline Hanoi Towers

on:
  push:
    branches:
      - master
      - staging
      - develop

jobs:
  accessibility:
    name: Web Accessibility Evaluation
    runs-on: ubuntu-latest
    steps:
     - name: Install Pa11y
       run: npm install -g pa11y-ci
     - name: Run Pa11y 
       run: pa11y-ci https://hanoi-frontend-prod-latest.onrender.com/
          
