name: CI Pipeline Hanoi Towers

on:
  push:
    branches:
      - master
      - staging
      - develop

jobs:
  accessibility:
    name: Web Accessibility Evaluation
    runs-on: ubuntu-latest
    steps:
     - name: Install Axe
       run: npm install @axe-core/cli -g
     - name: Install Chrome Driver Manager
       run: npm install -g browser-driver-manager
     - name: Install Chrome with Chrome Driver Manager
       run: npx browser-driver-manager install chrome
     - name: Run Axe 
       run: axe https://hanoi-frontend-prod-latest.onrender.com/
          
