name: CI Pipeline Hanoi Towers

on:
  push:
    branches:
      - master

jobs:
  accessibility:
    name: Accessibility Evaluation
    runs-on: ubuntu-latest
    environment: dev-accessibility
    steps:
     - name: Run App
       run: docker compose up
     - name: Install Axe
       run: npm install @axe-core/cli -g
     - name: Install Chrome Driver Manager
       run: npm install -g browser-driver-manager
     - name: Install Commander
       run: npm install commander -g
     - name: Install Chrome with Chrome Driver Manager
       run: npx browser-driver-manager install chrome
     - name: Install needed Chrome Version
       run: npm install -g chromedriver@125
     - name: Run Axe with set Chromedriver path
       run: axe --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver https://hanoi-frontend-prod-latest.onrender.com/, https://hanoi-frontend-prod-latest.onrender.com/game, https://hanoi-frontend-prod-latest.onrender.com/cheat, https://hanoi-frontend-prod-latest.onrender.com/solver --exit
          
