name: Use Hello World Action
on:
  push:
    # pull_request:
    branches:
      - setup/HANOI-TOWERS-T-36/basic-structure
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/hello-world-action
